my_list = [20, 60, 60, 12, 36]
print(my_list)
my_list.append(50)
print(my_list)
my_list.insert(2, 300)
print(my_list)
my_list.remove(20)
print(my_list)
my_list.pop(0)
print(my_list)
print(len(my_list))
my_list.sort()
print(my_list)
